### ISSUE TITLE
Gray folder for encripted database?

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1279]
Since its inception, the database has always colored the relevant folder in the sidebar yellow, if encripted.

However, I find myself on my OnePlus, an encripted database and the folder border totally gray: is this a bug or is something wrong?

![Screenshot_2022-11-01-14-37-29-47_28ac417cb9c2b686fc9f487d569b4fc7 (1)](https://user-images.githubusercontent.com/113377431/199246687-78815d66-edd9-4fd9-bcb3-bd88558cba4f.jpg)

**Comment by jr-simplex** [comment]
Hi

> Since its inception, the database has always colored the relevant folder in the sidebar yellow, if encripted.

Are you sure it said encrypted before and not vice versa? Orange icon means unencrypted database - it can only be so if you've had an application installed before this feature, and then migrated (or also possibly if you transferred unencrypted database from a terminal client).

If the one with gray icon is a new installation, the icon is gray because by default for new clients the database is encrypted on creation with a random password, which can be then changed.
