### ISSUE TITLE
Ring doesn't running when phone is locked and screen off

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1404]
Today I tried to make a call between two Android smartphones and I found that in one case (device A) SimpleX makes only one ringtone and after it is silent (but continue to ring silently).

In other case (device B) never gets ring on incoming call (with screen off and locked).

Device A: Motorola e7 plus Android 10
Device B: OnePlus Nord 2T 5G Android 12
Both running SimpleX 68 build

**Comment by epoberezkin** [comment]
Would you be able to help us debug this issue – we would send you a debug build that would do extra logging and we might be able to understand what is going on... Also, having logcat installed on your phone would help a lot – can you do it?

**Comment by avently** [comment]
@serrq do you still have these issues? As far as I remember, I made code changes related to this behaviour (not sure it was after or before you open this issue). Would be great if you can re-test and make sure that everything is working, otherwise I need to look at it closer again for finding a cause

**Comment by avently** [comment]
Thank you for confirming! Good to know that it's working as expected.
