### ISSUE TITLE
Multi-chat support

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1455]
We are close to an update that will bring privacy rules by group and by contact. Perhaps there is room for a further step.

Since it exists (I have not yet seen the system of restrictions, so I am assuming) a global recipe and a specific recipe (case by case), then I asked myself: «Why can't I open two (or more) chats with a same contact and submit different (privacy) recipes for each chat?»

For example I met a person on a language exchange platform, so I start a first chat for ordinary conversation (chat 1) and a second chat (chat 2) only for language exchange. Each chat, although it is the same contact, has a different privacy recipe.

The one destined for the linguistic exchange (chat 2) we have agreed to give permission to change each other's phrases in order to improve the construction of sentences in the learning of a foreign language.

In the chat 1 this permission is not necessary and we can talk about what interests us.

This opens the doors to thematic chats: just put a title on the chats, and one can understand with a quick glance what we are talking about. 
So possibly multiple chats, as well as having specific recipes, can also behave like notebooks divided by arguments.

So I imagine something like this:«Start a new chat with this contact» in the chat options.

**Comment by jr-simplex** [comment]
While there's no automation for the "Start a new chat with this contact" in-client, you can manually create additional connections with the same contact - just create an invitation link and share it with your contact in the existing conversation as you would do for any regular contact. You can assign different aliases locally for context. Also v4.3 will add connecting via a SimpleX link app in-app feature, so that it will no longer be necessary to copy/paste such links, they will initiate connection just by clicking.

As per specific preferences (rules), at least initially it will be a small curated list, without an ability to create custom preferences/features, such as editing other's messages, for example.

**Comment by PalmTamino** [comment]
> Just to have an idea about how to work the "edit each other messages" you can install "Tandem" app (https://www.tandem.net).
> 
> Thank you for your explanations and to invest your time to analyze my idea.

https://imgur.com/a/jPkoMPx
This is how it could look (Looks like this in Tandem)
