### ISSUE TITLE
Mobile data usage quite high on android

### ISSUE THREAD

**Issue by gitbq** [simplex-chat/simplex-chat#1515]
I just checked my phone data usage. I have shown the app, followed by each use type. 
Xmpp: various apps 76mb (medium usage) 
W: 400mb (high usage)
Sess: 50mb (medium useage)
Simplex: 1.85gb (low useage, just messages to test usability. No calling etc.)

Why is the Simplex data useage so high? 
Can this be rectified somehow? 

Device: pixel 4, calyx os, android 13.

**Comment by gitbq** [comment]
No groups. Just 4 contacts (my devices and developer) for testing messages. Average of 5 messages a day in total. Sent or received 10 pictures for the entire period.

**Comment by epoberezkin** [comment]
Yes, optimising traffic and battery consumption are priority for early next year. There are no silver bullets unfortunately (at least not the we know of), just many small things.

Some factors that will be keeping traffic higher:

1. fixed message size - whatever the content, SimpleX sends messages in 16kb block and any server replies are also in 16kb blocks, even if it's just ok. Clients and servers batch commands and replies when it is possible, but we do not delay sending for the purpose of batching - we could. I am very reluctant to make fixed block size optional, as not only it would reduce metadata privacy for users who choose to opt out, it will reduce metadata privacy for all users. But we will see.
2. decentralized groups.

Other than that, there are multiple things we should do around optimising retry strategies.

We will probably add some client-side telemetry first that users can submit, as aggregates, so we can better understand where the traffic is used - there might be some easy wins in the end.

**Comment by DeMoN100** [comment]
> I just checked my phone data usage. I have shown the app, followed by each use type. Xmpp: various apps 76mb (medium usage) W: 400mb (high usage) Sess: 50mb (medium useage) Simplex: 1.85gb (low useage, just messages to test usability. No calling etc.)
> 
> Why is the Simplex data useage so high? Can this be rectified somehow?
> 
> Device: pixel 4, calyx os, android 13.

Could you provide more specifics? On your contacts have you changed the traffic routing on any of them, do you use the tor option or not in network settings? Do you use a vpn on top of SimpleX? This could result in more traffic requests any other specifics I failed to think of may help give insight. 

In my own record as of November 1-30th I only have 1 contact and we have exchanged only 22 messages in that period of time. I have notifications on unrestrictived and battery optimization off for SimpleX  no modifications to traffic routing with tor when possible on. In that span my traffic has only been 9.52MB for the whole month of November. That may seem small but for one contact & only 22 messages exchanged to me in that amount of time that's a little alarming.

Now since I joined the SimpleX public group  in December my traffic has majorly spiked from December 1st till today the 10th my traffic has peaked to 20.87MB in only 10 days this to me is alarming. I think an investigation into this needs to happen and if you have to add telemetry to the app to solve it I will opt in just please remove the telemetry from the app once it has been concluded and a update has dropped to optimize the traffic.

**Comment by shumvgolove** [comment]
Let's discuss this in the `meta` issue: https://github.com/simplex-chat/simplex-chat/issues/1821

**Comment by RPLgrime** [comment]
> 1. fixed message size - whatever the content, SimpleX sends messages in 16kb block and any server replies are also in 16kb blocks, even if it's just ok. Clients and servers batch commands and replies when it is possible, but we do not delay sending for the purpose of batching - we could. I am very reluctant to make fixed block size optional, as not only it would reduce metadata privacy for users who choose to opt out, it will reduce metadata privacy for all users. But we will see.

Can you allow a toggle in settings where you can opt into waiting until aggregated user messages reach 16kb and form a block (slower service), or if your own message creates its own block (faster service)? I feel the required wait time would be under 2 seconds with the number of users active and would be negligible to most people.

**Comment by RPLgrime** [comment]
> as far as I understand it, servers have no way to know whether a message is less than 16kb, so you're just downloading each message as 16kb

Maybe the server could be split into two parts and a new script would be able to reroute a large message to Server1 and a small message to Server2.
Maybe like 16 character cutoff for the small server for when people say "Hi" or "Good morning" for example.

**Comment by CherrieTheShifter** [comment]
Yes This
