### ISSUE TITLE
Slide to send a message: to avoid accidental touches

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#1519]
![Screenshot_2022-12-07-13-32-47-15_28ac417cb9c2b686fc9f487d569b4fc7 (1)](https://user-images.githubusercontent.com/113377431/206180737-fa3dc240-353b-415c-9e7f-6cf49d264792.jpg)

Sometimes happens that keyboard is touched without an intention, by mistake, and a message can be send without our control.

I propose a "slide to left" action in order to send a message intentionally.

Or maybe is it better make long press on send button with a loading line that runs around the button perimeter?

**Comment by DeMoN100** [comment]
I think this is too much. How about the enter key doed not send the message and breaks line instead?

**Comment by DeMoN100** [comment]
> Maybe I understood. If "enter" key doesn't send message, which key do it send message?

You would just use the arrow instead of hitting enter. Then again my mobile keyboard does not send on hitting enter so I don't have this issue. I can accidently hit enter all day it won't send unless I hit the arrow.

**Comment by DeMoN100** [comment]
> 

I know what you mean. I'm just stating I don't have this issue maybe try an alternative keyboard. I am against the idea because its an accidential feature. In the video game industry this has become a popular feature because many gamers skip everything and accidently interact with a popup because they just have no patience. Since this had become a standard practice now it has always urked me to have to hold for 1-3 seconds to perform an action because the rest of society can't have patience and cautiously skip and not just spam on a button.

So to have this feature in a chat app the thought bothers me. Even if its made with an optional enable or disable so people like me will keep it disabled because we don't need it tjat would be nice but it would be bothersome that it's even there. Let the world be taught by mistakes so people will learn slow the hell down stop rushing take an extra second. It won't kill you to go over something an extra second.

I know the same could be said vice versa towards me but having to slide or holding for 1-3 seconds after i've already took the extra second to look over my spelling would just make me personally quit the app entirely because I have to do this every message.

**Comment by DeMoN100** [comment]
> I once read about a woman who accidentally sent sensual pictures (intended for her partner) in the school group of moms.
> 
> Of course the error was caused by distraction: having to produce an uncomfortable action, like dragging the button to the left, increases awareness of the action. It does not solve 100% but it offers the brain an extra obstacle to overcome in order to get to the goal.
> 
> In practical terms if that woman had the "slide to send" she probably would had to confront a further question before the final submission.

Thank you for proving my point. The lesson is that person needs to learn is to pay attention to what their doing. It's their own fault and it's their responsibility nobody elses. We don't have to cater to the prone to accident because they refuse to be aware or extra cautious. 

A slider won't increase awareness I don't know where you came up with this brain stimulation. If she had a brain she would have looked at her contacts because i'm sure her boyfriends name isn't mom. This is exactly what I was getting at in my previous comment. Learn from the mistake pay attention to what your doing and don't send nude pics to your mom lmfao.

**Comment by DeMoN100** [comment]
> Forgive me but you have a one-sided view of things. You do not allow the implementation of solutions for those who do not think like you.
> 
> I’m not trying to prove anything. I get no benefit from that woman sending or not sending naked pictures.
> 
> Prohibiting sending naked pictures or asking for maximum attention in a society that leads you to the practical and quick answer does not solve the question, as any person does not solve the addition 1+2 by setting fire to the exercise book or not writing it at all.
> 
> Despite your personal use of simplex, which I do not judge, I believe in the absolute innocence of that woman, who just wanted to make her partner share in her intimacy, right or wrong.
> 
> As a thinker or developer I have a moral duty to find a remedy, if a remedy is possible, so that in the future, a mother, a daughter, a colleague, does not send (accidentally) material without full awareness of it.
> 
> I don’t want to add anything else. This conversation is full of ideas. I presented the problem, the rest is not for me to decide.

Regardless of what you think of me I am going to voice my opinion on a feature wether I agree or disagree is my opinion. A one sided view no I look at it from all sides and for something like this I expressed why I disagree with this already. I'm going to assume because you are strongly hearted towards this story that it may have happened to a family relative or your own irrelvent.

This is a chat app and as secure as it can be does not mean the chat needs to or should be idiot proof. If you sent a message to the wrong person that is your fault not anyone elses or the developers. Next time look at the chat you tap on with your finger & look at the name displayed at the top before you hit the send arrow.

When it comes to features you should look at what's important and a nescessity to add while considering the preservation of space for it's file size also note the need of this feature. What your asking for is literally a convience safety measure for those who are careless to pay attention to what they are doing. I imagine the amount of users who really need this is most likely barely 1% & this request has no necessity of being essential to implement. So why should this make the app bigger and more inconvienent?

Look at the bigger picture and have a talk with the kid about paying attention and accepting responsibility of their own actions. Instead of looking to blame something else and being adamant that it should be in because of 1 individual incompetence.
