### ISSUE TITLE
Simplifying Incognito

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1678]
If I understand `Incognito` correctly, it looks to me that when enabled, whether we use our contact address or a one-time, the receiver will get a random profile. At that point I'm not sure what would be the difference between offering one or the other, but I guess a way to simplify this a little bit further it to just remove the `Incognito` option and provide another option in the menu where the addresses are managed — one for `Incognito`.

So in total it would be:

- `One Time` addresses
- `Incognito` — which looks very much like a one-time one address with a random profile
- The `Permanent` address

**Comment by ltGuillaume** [comment]
To make this more flexible, and considering people have opted they'd also like to use different "profiles" to connect to different people/groups, I'd like to propose the following:

![SimpleX-Invite](https://user-images.githubusercontent.com/4777345/210427632-d7b7ca3a-b61e-40e6-8224-922ef68e9233.png)
![SimpleX-Join](https://user-images.githubusercontent.com/4777345/210427637-89b4725b-d8a4-4c1d-839e-e75163331a1e.png)

A profile would just be the combination of display name, full name and avatar.

**Comment by epoberezkin** [comment]
Can you please explain what problem(s) does this proposal solve. I can guess of course, but I am interested to know how you see it - what are the problems of the current design and why the change is needed. Without agreement on the problem, considering proposals isn't too productive.

Also, the problem of the current designs are:
- doesn't scale well to a large number of profiles - while horizontal scrolling or dropdown can be used, they add to cognitive load. In any case, without agreeing on the problem we cannot find a better solution.
- in case "incognito" name is chosen, the contact still needs to be created in some of the profiles - and currently it's the profile that is currently active. In this case, when all profiles are listed, it is kind of confusing how to achieve creating incognito mode in a specific profile.

The started point is to articulate the problem and agree that it is substantial enough to justify the change.

**Comment by ltguillaume** [comment]
The biggest problem I have with the way things work now is that you can't choose the profile, or Incognito, after you clicked on or decided to share a link / QR (as in during the actual operation of joining/sharing).

Because you have to select the right profile beforehand, this easily causes the joining of groups with the wrong profile, because it's not an explicit part of the joining process. So you're at risk sharing more information about yourself than you wanted, simply because the first step of joining a group is on a whole different screen.

Also (and I haven't been using SimpleX extensively for a little while now, so it might have changed), if you click on a link like here https://github.com/simplex-chat/simplex-chat#join-user-groups while you're in a browser, how do you know as while profile you'll join?

The same thing goes for sharing a link/QR: the primary thought is "I want to connect to you", the secondary is "as who/using which profile".

**Comment by epoberezkin** [comment]
When connecting via the link from the outside it’ll connect using the currently active profile and current incognito mode setting - you can see it on the screen.

I understand that the inability to switch after making decision to connect make user to retrace their steps.

So it seems then that there are three problems here;

1. lack of clarity which profile is currently chosen in the screen where connection happens. An indication of the currently active profile is a minimal thing that’s needed to solve it.
2. The realisation that the currently chosen profile is wrong, and that is solved by some drop down where you can choose the active profile for this connection. That would be logical to also switch the UI by making the chosen profile active, as otherwise you won’t see the connection
3. The realisation that you want to connect with a random incognito name. That requires toggle in place - change of this toggle would also switch global default, not just change it for the current connection.

**Comment by epoberezkin** [comment]
In terms of complexity, simply showing active profile is simple, allowing to switch incognito mode is a bit more complex, allowing to change active profile after the one-time link is created is yet a more complex  problem.

**Comment by ltguillaume** [comment]
Yep, that sums it up quite nicely. I do have a question about (3), though.

Some more elaboration: the mock-up I made above indeed didn't take into account that separate profiles have separate conversation lists (it wasn't implemented yet back then). This creates the new situation where each profile has their own incognito conversations, and as such, simply putting Incognito as one of the "Invite as"/"Join as" options isn't a possibility anymore.

So yeah, with the current implementation, first step would be choosing your profile, the second would be a checkbox or something to enable incognito mode.

Changing the global switch, so that the last incognito mode choice is saved for the next invite/join makes sense.
