### ISSUE TITLE
Message Self

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1690]
This is an idea from other applications (in the field), where you can send messages to yourself. This is quite useful for quick notes, passing information between devices, etcetera.

Is this something that could be implemented in `SimpleX Chat`? — damn, I dislike that `Chat` word in the end :smile:

**Comment by ltGuillaume** [comment]
Depends on how you look at it:
1. This isn't possible until device syncing is implemented, OR
2. It's already possible by using two separate users 😛

**Comment by x80486** [comment]
Ah! I thought the application could be used with multiple devices and they would be in sync :thinking:

Anyway, I was more on the side that because the profile can change the address, probably it wouldn't be possible to do this, but at the same time, looks like one can delete and generate what's called a "temporary address" and previous contacts won't lose track — so a similar analogy might work with the `Self` approach.

**Comment by epoberezkin** [comment]
If you want to have some sort of notes / collections of links, you can create a group where you are the only member - these messages will be stored on your device and not sent anywhere. You can add other devices you have in this group for distribution.

Quite a few 1-2-1 conversations I have are actually groups too, with multiple devices of two people in them - it’s an old trick people use since WhatsApp

**Comment by theAkito** [comment]
Just make an empty group, with only you in it.

**Comment by x80486** [comment]
I get it, but I usually stay away from those workarounds, though I recognize they would work almost like the proper solution.

If this can be done properly it would be great. Also this is a concept that many people understand already from other applications.

**Comment by vsevolod-mineev** [comment]
I would also second the opinion that this is really needed. I use that feature a lot and would like to use SimpleX for it.

**Comment by theAkito** [comment]
> I get it, but I usually stay away from those workarounds, though I recognize they would work almost like the proper solution.

What exactly is the difference? In fact, there are apps, which automatically consider single-user groups as exactly this.

**Comment by x80486** [comment]
I can't tell what's the difference because I don't know the internals of `SimpleX Chat`.

I think the ticket is clear on how/what it should be. The complexity of _how to implement it_ should be simplified for the end user — they don't care if it's a private group or a single queue, or anything, as long as the UX is simple and the feature works as expected.

**Comment by bitjson** [comment]
I was also looking for this feature. I started by opening my own connection request with an incognito profile, but it's annoying to have two entries in the chat list and to get notifications on the other chat when sending a message (muting didn't seem to work either?).

It hadn't occurred to me create a secret group for this purpose until I read [@epoberezkin's comment](https://github.com/simplex-chat/simplex-chat/issues/1690#issuecomment-1372491933). That seems like the clear best solution – extends nicely to multiple devices and would eventually work seamlessly for profiles shared between devices (mobile/desktop). 

If I may suggest a UI to make this easier for new users to discover:

### Settings entry

Under `Settings` -> `You`, it would be great to have an additional entry labelled `Notes to Self` (material icon: [`Note stack`](https://fonts.google.com/icons?icon.style=Rounded&selected=Material+Symbols+Rounded:note_stack:FILL@0;wght@400;GRAD@-25;opsz@48&icon.query=note)). 

<img width="386" src="https://github.com/simplex-chat/simplex-chat/assets/904007/97a4fd43-9b22-4ed0-a07a-eb4bb518383b">

### "Notes to self" onboarding pane

On click, it opens a `Notes to Self` settings pane based on the `SimpleX address` pane prior to address creation:

<img width="385" src="https://github.com/simplex-chat/simplex-chat/assets/904007/1e6fd9ca-0603-49ba-bce8-3e8f95c9fadc">

Button: `Create "Notes to self"`, material icon: `Note stack`

Description: `Create a secret group called "Notes to self". These messages will be stored only on your device. You can also add other devices to the group to distribute new messages between devices.`

If `Notes to self` is mentioned in the [SimpleX Chat user guide](https://simplex.chat/docs/guide/app-settings.html) (e.g. [Signal's similar documentation](https://support.signal.org/hc/en-us/articles/360043272451-Note-to-Self)), an equivalent `About Notes to self` link at the bottom could link there.

### Post-creation

After the user has clicked the `Create "Notes to self"` button, the secret group is created with default settings, and the user is taken directly into the group chat. The UI should somehow uniquely mark this group to avoid it being confused with another group with the same name, e.g. Signal renders a small "blue check":

<img width="314" src="https://github.com/simplex-chat/simplex-chat/assets/904007/d6ba5882-d77f-43ef-99b9-1be40391a59b">

If the user now returns to the Settings screen and taps the `Notes to self` entry (under `You`), the UI should jump directly to the previously-created `Notes to self` chat, rather than displaying the above onboarding pane again.

**Comment by x80486** [comment]
Already implemented. The feature is named `Private Notes`: https://simplex.chat/blog/20240124-simplex-chat-infrastructure-costs-v5-5-simplex-ux-private-notes-group-history.html#private-notes
