### ISSUE TITLE
Would it be possible to implement real push notifications?

### ISSUE THREAD

**Issue by x80486** [simplex-chat/simplex-chat#1707]
I'm not sure what's the proper name for this, but I remember a couple of application that had the same issues with the battery before implementing push notifications. For instance, `Session` has both options: the background service, and the "fast mode" using Google's notification servers.

I guess there are always concerns around using anything Google, but since the messages are encrypted anyway, for some users it's more important to have a middle ground.

**Comment by ltGuillaume** [comment]
I use Blabber with a foreground service, instead of a push service + battery optimization disabled. It's very battery friendly. Granted, xmpp is a different protocol, but still I would say there's a lot of efficiency with the current method to be gained in SimpleX, without having to use Google's FCM.

**Comment by x80486** [comment]
I get it, but most people don't know how to go about it, or will be even against it with statements like "all the others work well but this one not" — which is at the stage I'm in at the moment :grimacing:

Also, having the option to select between the background service and Google's FCM should do it — even better with a small explanation on why to choose one or the other.

**Comment by theAkito** [comment]
When testing the app recently, I told someone to install the app & use it. I got a message two days later through a different communication channel, telling me, this app was uninstalled, because it sucked so much more battery, than all other apps, which already were one the phone.

So, yes, this is truly a huge issue, especially if you are on the go, which was the original intent of mobile phones...

**Comment by CherrieTheShifter** [comment]
Yes This
