### ISSUE TITLE
the ability to delete a message about a change in contact preferences (feature req.)

### ISSUE THREAD

**Issue by Wjxfi** [simplex-chat/simplex-chat#1790]
I've changed many times and now I have so many of these interfering messages that won't get deleted.

This is especially annoying when auto-delete mode is enabled. The whole chat is in these messages

 ‌
please add the ability to delete them
 ‌ ‌ ‌
>edit:
>
>
and the message of missed or unreceived or received calls (they are the same)

**Comment by epoberezkin** [comment]
Possibly we will allow deleting them selectively :)...

The will be all deleted if you "Clear chat"

**Comment by x80486** [comment]
I think the problem is that those don't get removed as well, even if the `Disappearing Messages` is enabled. It's a little bit annoying to go back and remove each one, because the calls also fall in that bucket, so at some point you will have a history that won't make sense because these are piling up at the beginning — I need to test this, so it's my guess based on the other applications I've used.

It's definitely a minor issue, but if those could be treated as the rest (and I think that's the problem :wink:) then it would work across the board.

**Comment by epoberezkin** [comment]
interesting... maybe they should be disappearing indeed.
