### ISSUE TITLE
[Feature request] Themes of the chat bubbles

### ISSUE THREAD

**Issue by WX4300** [simplex-chat/simplex-chat#1852]
I would love to adjust the colors of the chat bubbles (the most of my own bubbles but it would be nice to be able to adjust both of the bubbles)

**Comment by walteb** [comment]
I would also like to see this feature, or something like it, some day. The ability to color-code or otherwise flag a conversation is not *just* for fun. It can help to stay organized and provides some added visual context which might help to avoid the scenario where you accidentally send a message to the wrong person.

**Comment by epoberezkin** [comment]
You can do it in 5.1-beta.

And you can contribute your themes here: https://github.com/simplex-chat/simplex-chat/blob/master/docs/THEMES.md

**Comment by kremzli** [comment]
Should this be closed?
