### ISSUE TITLE
[bug]: opening Appearance menu on Android crashes on some devices

### ISSUE THREAD

**Issue by epoberezkin** [simplex-chat/simplex-chat#2130]
Most likely because of the languages.

e.g., GrapheneOS

also OneUI (Samsung's ROM)

**Comment by epoberezkin** [comment]
android.content.res.Resources$NotFoundException: Drawable chat.simplex.app:mipmap/icon_dark_blue with resource ID #0x7f0f0001\nCaused by:\nandroid.content.res.Resources$NotFoundException:\nFile res/la.xml from drawable resource ID #0x7f0f0001\n[...]

**Comment by avently** [comment]
This is caused by the following factors:
- when you build the apk, AAPT renames resources to something like xx.png, Xx.png, xX.png
- the apk gets unpacked by our script for compressing later
- your computer has a partition with case-insensitive file names
- after unpacking the apk, some files get deleted because they have identical names but with different case
- after re-archiving, the apk have lost these resources.

Solution:
- change filesystem of the partition where you have sources to case-sensitive type
- or we can change the script to un-archive one resources at a time and archiving it then one at a time for the whole `/res` directory

**Comment by avently** [comment]
Closed since it's fixed by https://github.com/simplex-chat/simplex-chat/pull/2138
