### ISSUE TITLE
Observer (lurker) mode decreases the security

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2146]
This new feature encourages remote stalking.

I understand from the beginning that it was inserted to never be removed but let me observe some injustices that this rule brings with it.

First, it offers the legislator a preferential way to "lie in wait" without being noticed.

Secondly, why should the group administrator see all members, including hidden members, while the members can only see what the little dictator expects them to see at this point?

This rule is Jeremy Bentham’s Panopticon put into practice, which is to observe without being observed.

I openly dissociate myself from this unfair practice in an app that should ensure the safety and freedom of all participants.

**Comment by epoberezkin** [comment]
I think you misunderstood what it does

**Comment by epoberezkin** [comment]
What observer role does is explained in this post: https://simplex.chat/blog/20230328-simplex-chat-v4-6-hidden-profiles.html#group--community-moderation

Is it how you understood it? Because I completely don’t understand the explanation of the problem. Probably you can explain in a simpler way, in which case it is a problem?
