### ISSUE TITLE
Should I hear a ringtone when I make an outgoing call?

### ISSUE THREAD

**Issue by qvsojBJGiEnR** [simplex-chat/simplex-chat#2636]
I just see a "starting..." and a "waiting for answer..." on Android, but I don't hear a ringing tone for outgoing audio and video calls.

Version: v.5.1.3

**Comment by epoberezkin** [comment]
No, there is no sound during the outgoing call. That's a bit of anachronism from analogue telephone networks, outgoing call is just a message you send, once the other side accepts it will start connecting. We might add some sound/haptic feedback for call progress, but "waiting" sound seems completely unnecessary...

**Comment by epoberezkin** [comment]
It's just an abstraction, you only really send one message, ringtones on the recipient side are completely independent, and they can turn them off instantly... The call can be accepted after any time while you keep it open - even in one hour, even next day - as long as you keep it open, while it will stop ringing at some point (I think), but the message in the chat can be used to accept (as long as the recipient chose ignore and not reject).

**Comment by epoberezkin** [comment]
we will see :) got the idea

**Comment by epoberezkin** [comment]
we will be revisiting calls experience at the same time we will be adding support for group calls. Ok to keep it open. It's likely to be 2024.

**Comment by x80486** [comment]
I have plenty of stories for this approach. This is one of the workflows that should be synchronous. If there are huge privacy concerns around it, have a toggle, in the same way currently one can select to relay or not. I just don't understand why it cannot be done (in the future) in such way that looks natural to every human being. Replicating `Signal` or `WhatsApp` for this should be the standard because. Messaging and calling are two completely different workflows.

For instance, there has been times that I've called friends and I've never received any feedback because they don't have good signal at that moment. After they are able to connect, they start receiving the call I made a few hours before.

And there is this issue also that to establish the calls it takes a long time. So everyone I know picks up saying several times: `hello`, `can you hear me?`, `are you there?` ...always, all the time — that one never fails :stuck_out_tongue_winking_eye:
