### ISSUE TITLE
[Q]: Windows extension?

### ISSUE THREAD

**Issue by paulsybrandy** [simplex-chat/simplex-chat#2673]
### Question

In the releases section there is a Windows release but there is no extension on the file which of courses causes it to not start and I am unsure what extension it should have to rename it to (.exe, .msi, etc.). Can someone please advise. Many thanks!

**Comment by spaced4ndy** [comment]
Hi, after downloading binary you should place it somewhere on PATH and add `.exe` extension to make it executable (placing on PATH is optional but otherwise you'd have to use full path to binary to run it). For example like here:

https://github.com/simplex-chat/simplex-chat/blob/stable/docs/CLI.md#windows

**Comment by paulsybrandy** [comment]
Thank you so much for that explaination. Worked like a charm! So many thanks.
