### ISSUE TITLE
Message disappear even if it is set OFF

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#2909]
This is not a feature: this is a backdoor for those that have a "special" edition of SimpleX.
They can always remove messages from recipient device because they always can set to 0 the variable.

Please fix this exploit.

**Comment by epoberezkin** [comment]
sorry, how does it work?

As long as disappearing messages are allowed in the conversation, the sender can set a custom time to disappear when sending the message. And this time can indeed be small.

**Comment by epoberezkin** [comment]
Nothing really changed in the protocol design - time to disappear has always been set per message, and any of the parties can change it - there is no mutual agreement about that time. This change is just a more convenient UI to do what was already possible, and also to make one message disappear if it is allowed (both sides have the toggle on) but not enabled (the time to disappear is set to "off").

There is a mutual agreement about allowing it though - so if this is prohibited it won't disappear.

Am I missing something the problem here?

**Comment by epoberezkin** [comment]
Yes, the difference between enabled and allowed is a bit confusing indeed.  But it seems ok as described, right?

**Comment by epoberezkin** [comment]
no problem, thanks!
