### ISSUE TITLE
[Q]: What is the future of simplex chat?

### ISSUE THREAD

**Issue by Darin755** [simplex-chat/simplex-chat#3115]
### Question

I noticed that the UK just passed a anti encryption law. Will this affect Simplex Chat? If so, is there any us servers I can use instead? I know the US isn't known for privacy but I figured its end to end encrypted anyway.

**Comment by epoberezkin** [comment]
Servers cannot compromise e2e encryption, and the position of the government is that as there is no technical possibility it won't be asked for. In any case the law doesn't mandate any client-side scanning, it only says that it can be requested.

So it doesn't matter where the servers are hosted. We host in the UK only because the provide better latency globally, even for the US.

**Comment by epoberezkin** [comment]
Going to close it. The future is bright, obviously :)
