### ISSUE TITLE
Use session's oxen nodes onion network instead of tor. Its specially designed for messangers and can run fast

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#3250]
This can heavily increase simplex anonymity and help run faster. Hope this can be fixed in the future.

**Comment by PLAYERUNKNOWNHatsune01** [comment]
No. Why you want to add Session crypto scam oxen network? And did you know that Oxen network store all the messages and metadata you sent on each nodes that it jump on for 15 days for no apparent reason. Give the devs one good reason to add this Network that basically runs on dying crypto scam. When Tor exist.

**Comment by vecna13** [comment]
This is probably in reference to Session messages being stored for 14 days to ensure cross-device deliverability. See [these](https://getsession.org/self-deleting-messages) [pages](https://sessionapp.zendesk.com/hc/en-us/articles/4416517720985-Why-do-disappearing-messages-reappear-after-restoring-my-Session-ID-). One consequence of this setting (as discussed in the second link) is that even when clients auto-delete "disappearing messages", these messages are still stored on a service node swarm for 14 days and can be re-downloaded and re-decrypted by new devices (due to lack of forward secrecy).

This particular issue wouldn't directly affect SimpleX if it used Lokinet for routing (since SimpleX messages wouldn't be stored on service node swarms like how Session messages are), but I think the argument being presented is it's a reason to distrust the whole Oxen/Session/Lokinet project.
