### ISSUE TITLE
push message to multiple sessions

### ISSUE THREAD

**Issue by ixzh** [simplex-chat/simplex-chat#337]
I opened two simplex-chat in two terminal windows. Both can send message, but only 1 (later opened) can receive message.  How can I have both sessions updated with received messages? Otherwise I will need to remember the last opened window to see the conversation.
Thanks

**Comment by epoberezkin** [comment]
The plan is to have a separate sub-protocol for client synchronisation, not to broadcast the messages to multiple clients.

There will also be another type of server with persistent messages that would support client broadcast - the current SMP servers are very low level queue brokers that only send messages to the last subscribed client by design and remove them as soon as the client acknowledges the reception - this is a convenient building block to construct more complex communication primitives.

A today’s workaround to receive messages to multiple clients with the existing design is to have different profiles and combine them into a group, together with a sender client(s) - not super convenient, but works…

**Comment by ixzh** [comment]
Thanks for the details!
