### ISSUE TITLE
Feature: Add some sort of privacy mode

### ISSUE THREAD

**Issue by User1l0** [simplex-chat/simplex-chat#3782]
Add a pricacy mode switch in chat preferences for example in dms you can restrict the other user to screenshot or download your content.

This should be in this app, please add this.

**Comment by ElonSatoshi** [comment]
First of all, there's no way to *guarantee* you can stop the other user from keeping anything. You should not send stuff to the user that they could ruin your life with by keeping. Anything that can be steamed and viewed on your phone can be saved, even if you have to alter the client to maliciously save stuff. Even the messages you already can delete in Simplex can be saved or retrieved using the CLI or the GUI's developer console. Even if permanent, full deletion is enabled instead of *marked deleted*.

There's no way to prevent someone from keeping something they downloaded, that they *have* to download in order to view. (pdfs, zips, things that aren't pictures/videos)

As for pictures, I don't know exactly what the logistics/ethics are of whether to make it possible to *force* the other person to not be able to take screenshots. Right now, the app has a toggle for whether or not the user wants the app to protect itself from screenshots.

In any case, if someone wants to screenshot your picture/message you don't want them to copy, they can just take a picture of the phone's screen with another camera.

Maybe, MAYBE it might be worth it to make it possible to send videos that stream instead of downloading? Again, the user could record it with another camera, or compile their own version of SimpleX Chat that downloads the video anyway.

**Comment by ElonSatoshi** [comment]
> > First of all, there's no way to _guarantee_ you can stop the other user from keeping anything. You should not send stuff to the user that they could ruin your life with by keeping. Anything that can be steamed and viewed on your phone can be saved, even if you have to alter the client to maliciously save stuff. Even the messages you already can delete in Simplex can be saved or retrieved using the CLI or the GUI's developer console. Even if permanent, full deletion is enabled instead of _marked deleted_.
> > There's no way to prevent someone from keeping something they downloaded, that they _have_ to download in order to view. (pdfs, zips, things that aren't pictures/videos)
> > As for pictures, I don't know exactly what the logistics/ethics are of whether to make it possible to _force_ the other person to not be able to take screenshots. Right now, the app has a toggle for whether or not the user wants the app to protect itself from screenshots.
> > In any case, if someone wants to screenshot your picture/message you don't want them to copy, they can just take a picture of the phone's screen with another camera.
> > Maybe, MAYBE it might be worth it to make it possible to send videos that stream instead of downloading? Again, the user could record it with another camera, or compile their own version of SimpleX Chat that downloads the video anyway.
> 
> Yeah but for a such privacy app, there should be a feature like this

Maybe not, because it could give users a false sense of security.

**Comment by ElonSatoshi** [comment]
> > you shouldn't rely on screenshot restrictions to protect yourself, they can always be bypassed and are not reliable, when it matters they will fail
> 
> Not anyone has a time to bypass some conversation. Not everyone is a hacker developer you know? It just need to be there so it can give some privacy

You don't need to be a hacker developer to take a picture of your phone's screen with another phone.
