### ISSUE TITLE
Desktop app (GUI)

### ISSUE THREAD

**Issue by arch-btw** [simplex-chat/simplex-chat#425]
Hi,

Thank you for this project. It's great to have a new secure messenger. 

My suggestion is to make a GUI desktop app for Linux.

Thank you for your consideration.

**Comment by epoberezkin** [comment]
Thank you for the suggestion! we will be looking into desktop app some time later this year, we do not have capacity for it right now I am afraid.

I am happy to support and guide if somebody would be interested to build a desktop app, it is not a small project though.

**Comment by snakyjake1** [comment]
> we will be looking into desktop app some time later

Hopefully a cross-platform framework to make development simple and the UI consistent is possible.  Some people may also like using a web app.

**Comment by Icy-Thought** [comment]
@epoberezkin don't know how beneficial this comment will be, but you might want to take a look at [Monomer](https://github.com/fjvallarino/monomer) and perhaps even consider it a qualifying GUI library for the upcoming desktop client? :smile:

**Comment by guglovich** [comment]
I also find the fresh but ready for release, [Iced](https://iced.rs/), interesting. And also [Slint](https://slint-ui.com/).

**Comment by epoberezkin** [comment]
> Not enough to just have the desktop client. Perfectly you'd have the message sync with the mobile somehow.

100%. That's actually #1 reason why we didn't spend any effort on desktop client, without some solution for sync it's much less valuable. It is coming in 2023.

**Comment by x80486** [comment]
> I am happy to support and guide if somebody would be interested to build a desktop app, it is not a small project though.

If you would like to I can start something. It would really depend on the stack you would like to use. I really don't have much experience on anything-desktop, but usually `Electron` (The Most Useful and Hated™) is a pretty good solution to cover almost all mainstream desktops — not to mention the community and support behind it. Wails also looks great...and `Go` is never a bad choice.

I understand you don't have a way to synchronize multiple devices, but that could be an addition down the line.

Anyway, up to you...let me know.

**Comment by Josh-SMU** [comment]
I think having a non-linked desktop GUI is still really important, as not only does it allow a desktop to be used for communication but also Linux phones such as the Pinephone and Librem5.

**Comment by roihershberg** [comment]
Have you thought on using [Compose Multiplatform](https://www.jetbrains.com/lp/compose-mpp/) and thus sharing the same UI with the Android app and hopefully the majority of the code? I think it avoids the burden of maintaining another framework and another codebase. I looked at the Android code and it looks HUGE. A few files but every one of them with thousands of lines. I have some experience with writing Android apps and maybe if someone can guide me through the code we can look if it's possible to seperate cleanly the code that is not related to the Android platform (except Compose) so that it can be shared with the desktop app. It it's doable maybe I can start working on it.

**Comment by Hasshu** [comment]
Speaking of Linux, to make the desktop version as distro-agnostic as possible, consider eventually releasing it as a static (read "portable") build and/or a Flatpak.

**Comment by Greenheart** [comment]
Since maintaining a desktop app (and ideally also a web app) requires significant work, it might be beneficial to build on top of a framework that creates a secure foundation for a desktop app, while allowing the UI to be created with web technologies that allow more people to contribute. Using this architecture would also allow re-using the desktop UI for a future web app.

One promising solution is https://tauri.app/ built with Rust, is more secure, and much more lightweight compared to the infamously resource-hungry https://www.electronjs.org/ (since Tauri re-uses the built-in native WebView).

For the web UI, I can highly recommend https://svelte.dev/ and https://tauri.app/v1/guides/getting-started/setup/sveltekit/ to optimise for DX and app performance.

This proposal could solve https://github.com/simplex-chat/simplex-chat/issues/747 at the same time.

**Comment by trymeouteh** [comment]
I would like to see a desktop app for Windows, MacOS and Linux. I hope it is build using as much of the codebase in the mobile apps.

**Comment by link-leocorde** [comment]
Would definitely love to see a desktop client. Let me know if there's any way I can help contribute (not a programmer). Threema has an interesting one where it connects to the mobile instance and that seems to work really great.

**Comment by shumvgolove** [comment]
Let's continue discussion here: https://github.com/simplex-chat/simplex-chat/issues/2281 Thanks!
