### ISSUE TITLE
[Bug]: Wallpaper repeating don't work

### ISSUE THREAD

**Issue by summoner001** [simplex-chat/simplex-chat#4303]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Linux, Android

### OS version

Arch Linux / Android 9

### App version

V5.8.0

### Current Behavior

When I set a wallpaper like this:

![bg](https://github.com/simplex-chat/simplex-chat/assets/11212632/24d2225b-b84b-4168-b640-0ad9a03309ba)

or any other extended image like: jpg/jpeg/png/gif and I select the repeat mode. The wallpaper is gone, and only the background color is visible

### Expected Behavior

Show repeated or mosaik wallpaper.

### Steps To Reproduce

1) choose your custom wallpaper
2) select repeat wallpaper mode

**Comment by avently** [comment]
First of all, it's a gif. Secondly, it doesn't have a transparent background. 
For this type of wallpaper to work you need a transparent png image like:
https://duckduckgo.com/?q=transparent+pattern&t=fpas&iax=images&ia=images&iaf=size%3AMedium&iai=https%3A%2F%2Fwww.pngall.com%2Fwp-content%2Fuploads%2F14%2FPattern-PNG-Image-HD.png

So you customize the wallpaper background color. Then move the opacity slider of the wallpaper accent color to the left side in order to see it (by default it's fully transparent).

**Comment by summoner001** [comment]
Aaaa. I understand. Thank you so much!
Have a nice day!
