### ISSUE TITLE
Telegram CEO Pavel Durov was reportedly arrested in France on Saturday over charges related to illegal activity on the messaging platform

### ISSUE THREAD

**Issue by serrq** [simplex-chat/simplex-chat#4758]
https://www.dw.com/en/telegram-founder-pavel-durov-arrested-in-france/a-70042055

“Durov is suspected of failing to take measures to curb the use of his platform for criminal purposes.”

EU attacks freedom. This change everything. We have to prepare to the worst scenario. 

In my opinion here in SimpleX we have to separate messaging app from e2ee, so that encryption become an external add-on.
Or maybe even better a layer 1 e2ee for governments (encryption with backdoors), and an optional layer 2 encryption for the rest of us (the true encryption) as add-on solution.

**Comment by Arturro43** [comment]
„we have to separate messaging app from e2ee, so that encryption become an external add-on.”

No offense, but this is the dumbest idea I’ve ever heard.

1. There’s NO privacy without encryption. If you don’t want e2e encryption by default then go for IRC or Telegram (lack of e2ee didn’t help Telegram’s CEO, I guess).

Your proposal is absolutely against vision behind SimpleX. SimpleX was founded to give people privacy and (ultimately) anonymity.

„Privacy in an open society also requires cryptography. If I say something, I want it heard only by those for whom I intend it. If the content of my speech is available to the world, I have no privacy. To encrypt is to indicate the desire for privacy, and to encrypt with weak cryptography is to indicate not too much desire for privacy.” - Eric Huges, A Cypherpunk's Manifesto, 1993

https://simplex.chat/blog/20240601-protecting-children-safety-requires-e2e-encryption.html

2. I bet Evgeny would do the same thing Meredith, CEO of Signal said. https://x.com/mer__edith/status/1796508893822238881

„Let there be no doubt: we will leave the EU market rather than undermine our privacy guarantees. 

This proposal--if passed and enforced against us--would require us to make this choice. 

It's surveillance wine in safety bottles.”

3. Where is your will to fight for fundamental human right, god damn it? If someone were to take property from you by force, wouldn't you be against it?
Pardon my language, but when government introduces new law which is against your views do you fire up full bootlicker mode and just try to live with it? Is this our future? Are we giving up our rights… just like that?

Well, I cannot agree with that vision and I think many others can relate.
I’ve spent hours upon hours translating SimpleX docs to my first language completely for free. Why? Because SimpleX isn’t like any other instant messenger and I believe in SimpleX.

SimpleX is here to stay and to introduce new, absolutely outstanding features that are aimed to improve privacy even more. If your goal was to scare founders and/or contributors of SimpleX then…

nice try fbi
