### ISSUE TITLE
[Q]: Why is it necessary to be on the same local network for "Use from desktop"? 

### ISSUE THREAD

**Issue by SebasKoel** [simplex-chat/simplex-chat#5019]
### Question

Why is it necessary to be on the same local network for "Use from desktop"?  This causes problems when being connected to a vpn or when on 4g without wifi which connects both devices.

**Comment by taovuokko** [comment]
I've noticed the same issue. After looking into it, I realized this is likely due to security concerns. Using the phone as an intermediary ("streamer") prevents the desktop from becoming an independent receiving device, ensuring that sensitive data is not stored or exposed on the desktop, which could be more vulnerable to attacks.

Restricting connections to a local network reduces the risk of interception or unauthorized access. For example, Signal’s desktop app has had multiple security vulnerabilities in the past, so this approach likely aims to minimize similar risks and ensure tighter control over data flow.
