### ISSUE TITLE
[Bug]: Unable to connect Android client with Windows client

### ISSUE THREAD

**Issue by cstm-dev** [simplex-chat/simplex-chat#5060]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Platform

Windows, Android

### OS version

Android 14, Windows 11

### App version

6.1

### Current Behavior

When I want to connect my Android client with my computer I get the following error message. 

```
{
    "type": "connectionFailed",
    "chatError": {
        "type": "errorAgent",
        "agentError": {
            "type": "RCP",
            "rcpErr": {
                "type": "exception",
                "exception": "HandshakeFailed (Error_Protocol \"certificate has expired\" CertificateExpired)"
            }
        }
    }
}
```

I use the app for some months now and everything was fine until shortly before 6.1 release. In the past I had to try to connect multiple times before it worked though.

### Expected Behavior

The Android client is able to connect to the Windows client.

### Steps To Reproduce

Open the Windows application and enter the database password.
Click "Link a mobile"
Open the Android application
Click "Use from Desktop"
Scan the QR Code

### Relevant log output

```shell
{
    "type": "connectionFailed",
    "chatError": {
        "type": "errorAgent",
        "agentError": {
            "type": "RCP",
            "rcpErr": {
                "type": "exception",
                "exception": "HandshakeFailed (Error_Protocol \"certificate has expired\" CertificateExpired)"
            }
        }
    }
}
```
```

**Comment by XCanG** [comment]
I have somewhat similar issue, but I think it's because of a different reason. I installed SimpleX yesterday on PC and Android, in Google Play it downloaded version `6.0.1-5`, on PC it's the latest `6.1 (73)`. When I scan QR code I get an error that version is not compatible.

Because your last release on Github was 5 days ago I can only suspect that the app is taking time to verify by Google Play store, before it publish new version, but this kind of issue is not convenient at all. There should be solution that will be able to pair devices for any minor version differences, I will agree that it may not be able to pair version `6.*` with version `7.*`, but `6.0` should be able to pair with `6.1`, `6.2`, etc...

**Comment by Headedbranch225** [comment]
I think the same issue is happening with the f-droid version, I just installed the apk directly and it works

**Comment by cstm-dev** [comment]
> I get this error when my computer's clock does not match, could you double check your devices' time?

Mate, you made my day. Not in a million years I would have thought, that this might cause the issue. That solved it for me. Windows time was wrong, even though the sync was on. Probably didn't reach the time server... as usual.

Thanks again.
