### ISSUE TITLE
[Enhancement / Feature Request] Thread for file size optimizations

### ISSUE THREAD

**Issue by abrasmag3** [simplex-chat/simplex-chat#817]
The files for SimpleX Chat are pretty large, especially the Android APK. This is largely (as far as I know) due to how Haskell compiles. There are a few common solutions for this stated online, but I can't be sure if they are applicable to SimpleX, or even if they have already been implemented.

- [ ] Avoiding large dependencies as much as possible. Kitchen-sink isn't really worth it in a statically linked compile unless you use the whole sink. Many small dependencies will often quietly depend on very large ones as well.
- [ ] Windows and some Linux distributions support dynamically linked Haskell, but doing so requires the destination to have the libraries installed.
- [ ] Removing the symbols from release versions using `strip`, as they are only useful for debugging and not for the average user.
- [ ] Using `upx`, an executable compressor. It reduces the file size often by 5-6x in Haskell, but since it needs unpacking before running, it's inefficient when running multiple instances of the same executable.
- [ ] Avoid using `Read`, because it's unnecessarily slow.

I'm not familiar enough with Haskell to know for sure how useful these are in this project, but even if none of them are, I hope other ideas come up here.

For the APK specifically, optimizing the dex files may help.

**Comment by abrasmag3** [comment]
Note: my main source is this blog post, https://dixonary.co.uk/blog/haskell/small

It shows how much of a difference changing dependencies can make, as well as `-dynamic`, `strip`, and `upx`

**Comment by avently** [comment]
>Avoiding large dependencies as much as possible

No unneeded dependencies currently from Haskell part

>Windows and some Linux distributions support dynamically linked Haskell

Not an option. Haskell binaries requires tens of libs to be installed and maintained. It's almost like npm but with system package manager. Having tens of Haskell dependencies because of just one app is not a comfortable solution for end users.

> Using upx, an executable compressor.

As far as I know, it don't work with libs on Android. It can be applied to desktop executables but desktop executables aren't so big.

> For the APK specifically, optimizing the dex files may help.

Here we have a place for optimization. We use one large lib that can be removed and replaced with parts of it. Or even can optimize Proguard that will stript unneeded code. Currently it can save 10 mb out of 40-50 I think. 
There is an optimization that was made to non-Google play apk in terms of apk compression. Size was dropped from 200 to 40-50.
https://github.com/simplex-chat/simplex-chat/blob/stable/scripts/android/compress-and-sign-apk.sh

**Comment by mika-nl** [comment]
Why is it only non-google playstore ?

**Comment by epoberezkin** [comment]
closing it.

> Why is it only non-google playstore ?

Not sure what you mean. Google play store always had it even smaller, they apply some more aggressive compression.
